baseURL = "https://incrediblegoblin.com/"
languageCode = "ru-ru"
title = "Gøblin"
theme = "gbln"

copyright = " © "

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

defaultContentLanguage = "ru"

[params]
    favicon = "/icons/favicon.ico"
    disableDisqusTypes = ["page"]
    featherIconsCDN = true
    mode = "light"  # "dark", "auto", "light"
    mainSections = ["programming", "travel"]
	subtitle = "Твоя худшая встреча этим летом"

[services.disqus]
    shortname = "your-disqus-shortname"

summaryLength = 20

[[menu.main]]
name = "Главная"
url = "/"
weight = 1

[[menu.main]]
name = "Путешествия"
url = "/posts/travel"
weight = 2

[[menu.main]]
name = "Обо мне"
url = "/about"
weight = 4

[[menu.main]]
name = "Велопедеразм"
url = "/posts/bicycle"
weight = 3

[[menu.main]]
name = "Поиск по тегам"
url = "/tags"
weight = 5

[[params.social]]
name = "Отчёты из приюта"
icon = "/icons/dog-icon.svg"
url = "/posts/dogshelter"
[[params.social]]
name = "Github"
icon = "/icons/github-mark.svg"
url = "https://github.com/ImGoblin"
[[params.social]]
name = "Telegram"
icon = "/icons/TGLogo.svg"
url = "https://t.me/itisgoblin"


[taxonomies]
   tag = "tags"

[Languages]
[Languages.ru]
languageName = "Русский"